[package]
name = "server_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_renet = "0.0.12"
protos = { version = "0.1.0", path = "../protos" }
